class ObsidianLazyCommit < Formula
  desc "Scheduled auto-commit and push for one or more Obsidian vaults via launchd"
  homepage "https://github.com/acarmisc/obsidian-lazy-commit"
  url "https://github.com/acarmisc/obsidian-lazy-commit/archive/refs/tags/v1.2.0.tar.gz"
  sha256 "43b55fc938ee9cc45fd89e9c8585af3aae5de8383234d4ba05b3c06d627a7ce3"
  version "1.2.0"
  license "MIT"

  depends_on :macos => :tahoe

  def install
    # Public entry points.
    bin.install "bin/obsidian-lazy-commit"
    bin.install "bin/obsidian-lazy-commit-setup"

    # The per-tick script. libexec is the conventional place for scripts a
    # formula runs itself; it survives `brew upgrade` without stale copies.
    libexec.install "commit.sh"

    # Sample config so users have something to copy from.
    # Only write if it doesn't exist — re-installs shouldn't clobber
    # user-edited copies.
    (etc/"obsidian-lazy-commit").mkpath
    example = etc/"obsidian-lazy-commit/config.toml.example"
    unless example.exist?
      example.write <<~TOML
        # Sample config for obsidian-lazy-commit.
        # Copy to ~/.config/obsidian-lazy-commit/config.toml and edit.
        # After editing, run `obsidian-lazy-commit-setup` once to register
        # the launchd job.

        schedule_seconds = 3600

        [[vaults]]
        name = "main"
        # Replace with the absolute path to your Obsidian vault.
        path = "/Users/YOU/Documents/ObsidianVault"
        # Replace with your repo URL, or set to "" to keep commits local.
        remote = "git@github.com:YOUR_USER/YOUR_REPO.git"
        branch = "main"
      TOML
    end
  end

  def post_install
    # Friendly nudge: don't run setup automatically (it's interactive).
    # The user's first `obsidian-lazy-commit-setup` will write the
    # real config and load the launchd job via brew services.
  end

  service do
    # The launchd plist is generated by Homebrew from this block.
    # brew services uses homebrew.mxcl.<name> as the label.
    #
    # macOS launchd note: this tool reads the user's vault files
    # under $HOME, and macOS TCC blocks non-Aqua launchd jobs
    # from accessing files in the user's home directory. The
    # brew-generated plist allows Aqua/Background/etc, but in
    # practice the user should run `brew services start` from
    # a regular Terminal.app session so the job is bootstrapped
    # in Aqua and inherits the right TCC rights. If the job logs
    # show "fatal: Unable to read current working directory:
    # Operation not permitted", run `obsidian-lazy-commit --self-heal`.
    run [libexec/"commit.sh"]
    environment_variables(
      PATH: "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin",
    )
    keep_alive false
    run_at_load false
    interval 3600
    log_path "/tmp/obsidian-lazy-commit.log"
    error_log_path "/tmp/obsidian-lazy-commit.err"
    working_dir HOMEBREW_PREFIX
  end

  def caveats
    <<~EOS
      obsidian-lazy-commit has been installed. To finish setup:

        1. Run `obsidian-lazy-commit-setup` (interactive) to declare
           your vaults and the schedule. It writes:
             ~/.config/obsidian-lazy-commit/config.toml

        2. Start the launchd job:
             brew services start obsidian-lazy-commit

      Logs are at:
        /tmp/obsidian-lazy-commit.log
        /tmp/obsidian-lazy-commit.err

      To stop the job: brew services stop obsidian-lazy-commit
      To see status:   brew services info obsidian-lazy-commit
    EOS
  end

  test do
    # Smoke test: the wrapper should exit with an instructive message when
    # no config exists (also verifies the entry point runs).
    assert_match "obsidian-lazy-commit-setup",
                 shell_output("#{bin}/obsidian-lazy-commit 2>&1", 1)
  end
end