class ObsidianLazyCommit < Formula
  desc "Scheduled auto-commit and push for one or more Obsidian vaults via launchd"
  homepage "https://github.com/acarmisc/obsidian-lazy-commit"
  url "https://github.com/acarmisc/obsidian-lazy-commit/archive/refs/tags/v1.1.0.tar.gz"
  sha256 "3c2ebef3e9870126fb9b07a7c35a32afc20097351e77f34f5d36c352b3a3ff58"
  version "1.1.0"
  license "MIT"

  depends_on :macos => :tahoe

  def install
    # Binaries (thin wrappers that exec the real scripts).
    bin.install "bin/obsidian-lazy-commit"
    bin.install "bin/obsidian-lazy-commit-setup"
    bin.install "bin/obsidian-lazy-commit-commit"

    # The actual per-tick script and plist template live in share/, so
    # they survive `brew upgrade` without leaving stale copies in bin/.
    (share/"obsidian-lazy-commit").install "commit.sh"
    (share/"obsidian-lazy-commit").install "com.user.obsidian-lazy-commit.plist"

    # Substitute the HOMEBREW_PREFIX sentinel in commit.sh so the
    # wrapper can locate the real script via $HOMEBREW_PREFIX/share/...
    inreplace (share/"obsidian-lazy-commit/commit.sh"),
              "@@HOMEBREW_PREFIX@@", HOMEBREW_PREFIX.to_s

    # Sample config so users have something to copy from.
    # Only write if it doesn't exist — re-installs shouldn't clobber
    # user-edited copies.
    (etc/"obsidian-lazy-commit").mkpath
    example = etc/"obsidian-lazy-commit/config.toml.example"
    unless example.exist?
      example.write <<~TOML
        # Sample config for obsidian-lazy-commit.
        # Copy to ~/.config/obsidian-lazy-commit/config.toml and edit.
        # After editing, run `obsidian-lazy-commit-setup` once to register
        # the launchd job.

        schedule_seconds = 3600

        [[vaults]]
        name = "main"
        # Replace with the absolute path to your Obsidian vault.
        path = "/Users/YOU/Documents/ObsidianVault"
        # Replace with your repo URL, or set to "" to keep commits local.
        remote = "git@github.com:YOUR_USER/YOUR_REPO.git"
        branch = "main"
      TOML
    end
  end

  def post_install
    # Friendly nudge: don't run setup automatically (it's interactive).
    # The user's first `obsidian-lazy-commit-setup` will write the
    # real config and load the launchd job via brew services.
  end

  service do
    # The launchd plist is generated by Homebrew from this block.
    # brew services uses homebrew.mxcl.<name> as the label.
    #
    # Why `LimitLoadToSessionType: Aqua` (and not the brew default of
    # Aqua/Background/etc): this tool reads the user's vault files
    # under $HOME, and macOS TCC blocks non-Aqua launchd jobs from
    # accessing files in the user's home directory. If the job runs
    # in a Background session, `git rev-parse` fails with
    # "fatal: Unable to read current working directory: Operation not
    # permitted". Aqua-only restricts the job to user sessions, which
    # is fine for a per-user commit tool.
    run [opt_bin/"obsidian-lazy-commit-commit"]
    environment_variables(
      PATH:            "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin",
      HOMEBREW_PREFIX: HOMEBREW_PREFIX.to_s,
    )
    keep_alive false
    run_at_load false
    interval 3600
    log_path "/tmp/obsidian-lazy-commit.log"
    error_log_path "/tmp/obsidian-lazy-commit.err"
    working_dir HOMEBREW_PREFIX
    limit_load_to_session_type "Aqua"
  end

  def caveats
    <<~EOS
      obsidian-lazy-commit has been installed. To finish setup:

        1. Run `obsidian-lazy-commit-setup` (interactive) to declare
           your vaults and the schedule. It writes:
             ~/.config/obsidian-lazy-commit/config.toml

        2. Start the launchd job:
             brew services start obsidian-lazy-commit

      Logs are at:
        /tmp/obsidian-lazy-commit.log
        /tmp/obsidian-lazy-commit.err

      To stop the job: brew services stop obsidian-lazy-commit
      To see status:   brew services info obsidian-lazy-commit
    EOS
  end

  test do
    # Smoke test: the wrappers should at least respond to `--help`-style
    # invocations. We invoke the default wrapper, which will exit with
    # an instructive message if no config exists.
    assert_match "obsidian-lazy-commit-setup",
                 shell_output("#{bin}/obsidian-lazy-commit 2>&1", 1)
  end
end
